### PR TITLE
remove -j optiion

### PR DESCRIPTION
**Pull request by tkmru**
I tried to install pwntools-binutils in mac, but terminal freezed. The cause was  'make -j'. 'j option' make so many jobs. It is heavy. Non option is better

### CODE REVIEW

**Comment by kokjo** [comment]
No, -j is better for most people.

**Comment by zachriggle** [comment]
Agreed

**Comment by tkmru** [comment]
My mac spec is memory 8GB, CPU corei5 1.4Ghz. I think that it is high peformance. Don't you think this case is dangerous?

**Comment by zachriggle** [comment]
The -j flag should use all of you CPUs. If you're doing something else, it will probably slow down.  On a 2014 retina MacBook pro, it takes about 60 seconds to compile binutils.  Extending that to 8 minutes is not acceptable.

**Pull request closed without merging**
